run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

linters-settings:
  govet:
    enable-all: true
  gosec:
    excludes:
      - G104 # Audit errors not checked (handled by errcheck)

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
